type Category = "Habilidades" | "Herramientas" | "Puestos" | "Idiomas" | "Formación";
type Detected = { label: string; category: Category };
const catalog: Record<Category, string[]> = {
  Habilidades: ["liderazgo", "comunicación", "comunicacion", "negociación", "negociacion", "ventas", "análisis", "analisis", "planificación", "planificacion", "estrategia", "atención al cliente", "atencion al cliente", "trabajo en equipo", "gestión de proyectos", "gestion de proyectos", "resolución de problemas", "resolucion de problemas"],
  Herramientas: ["excel", "power bi", "sql", "python", "javascript", "typescript", "react", "sap", "salesforce", "crm", "jira", "trello", "tableau", "figma", "google analytics", "adobe", "office"],
  Puestos: ["analista", "desarrollador", "developer", "diseñador", "disenador", "vendedor", "ejecutivo", "asistente", "coordinador", "gerente", "manager", "recruiter", "administrativo", "contador", "marketing", "customer success", "product manager"],
  Idiomas: ["inglés", "ingles", "portugués", "portugues", "francés", "frances", "bilingüe", "bilingue"],
  Formación: ["universitario", "universidad", "terciario", "técnico", "tecnico", "licenciatura", "ingeniería", "ingenieria", "marketing", "administración", "administracion", "contabilidad", "sistemas", "informática", "informatica"],
};
function normalize(text: string) { return text.toLocaleLowerCase("es").normalize("NFD").replace(/[\u0300-\u036f]/g, ""); }
function contains(text: string, term: string) { const escaped = normalize(term).replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); return new RegExp(`(?:^|\\W)${escaped}(?:$|\\W)`, "i").test(normalize(text)); }
function findTerms(text: string): Detected[] { return Object.entries(catalog).flatMap(([category, terms]) => terms.filter((term) => contains(text, term)).map((label) => ({ label, category: category as Category }))); }
function years(text: string) { return [...text.matchAll(/(\d+)\s*(?:años|anos|year|years)/gi)].map((match) => Number(match[1])).sort((a, b) => b - a)[0] ?? 0; }
function evidence(cv: string, labels: string[]) { return cv.split(/(?<=[.!?\n])\s+/).map((part) => part.trim()).filter((part) => part.length > 25 && labels.some((label) => contains(part, label))).slice(0, 4); }
export function analyze(jobDescription: string, cvText: string, cvFileName: string) {
  const jobTerms = findTerms(jobDescription); const cvTerms = findTerms(cvText); const jobLabels = [...new Set(jobTerms.map((term) => term.label))]; const cvLabels = new Set(cvTerms.map((term) => term.label)); const matched = jobLabels.filter((term) => cvLabels.has(term)); const missingKeywords = jobLabels.filter((term) => !cvLabels.has(term)).slice(0, 10);
  const categories: Category[] = ["Habilidades", "Herramientas", "Puestos", "Idiomas", "Formación"]; const categoryResults = categories.map((category) => { const required = jobTerms.filter((term) => term.category === category).map((term) => term.label); const found = required.filter((term) => cvLabels.has(term)); return { category, required: [...new Set(required)], found: [...new Set(found)] }; });
  const jobYears = years(jobDescription); const cvYears = years(cvText); let score = jobLabels.length ? Math.round((matched.length / jobLabels.length) * 75) : 25; score += jobYears ? (cvYears >= jobYears ? 15 : cvYears ? 8 : 0) : cvYears ? 12 : 4; score = Math.min(98, Math.max(8, score));
  const strengths = categoryResults.filter((result) => result.found.length).slice(0, 4).map((result) => `${result.category}: ${result.found.join(", ")}`); const gaps = categoryResults.filter((result) => result.required.length && result.found.length < result.required.length).map((result) => `${result.category}: faltan ${result.required.filter((term) => !cvLabels.has(term)).slice(0, 3).join(", ")}`); if (jobYears && cvYears < jobYears) gaps.push(`Experiencia: el aviso menciona ${jobYears} años y el CV evidencia ${cvYears || "no especifica"}.`);
  const relevantExperience = evidence(cvText, matched).map((sentence) => `“${sentence.slice(0, 180)}${sentence.length > 180 ? "..." : ""}”`); const recommendations: string[] = []; if (missingKeywords.length) recommendations.push(`Revisá si podés describir con evidencia del CV estos requisitos: ${missingKeywords.slice(0, 5).join(", ")}.`); if (jobYears && cvYears < jobYears) recommendations.push("Ordená tu experiencia por relevancia y explicitá los años que ya aparecen respaldados en tu CV."); if (!recommendations.length) recommendations.push("Priorizá en el resumen y en cada experiencia los términos del aviso que ya están presentes en tu CV."); recommendations.push("Usá logros concretos y medibles solo cuando estén respaldados por tu experiencia real.");
  const highlight = strengths.length ? strengths.slice(0, 3).map((item) => `Destacá ${item.toLocaleLowerCase("es")} con ejemplos concretos del CV.`) : ["Reforzá el resumen profesional usando únicamente información que ya figure en tu CV."]; const summary = score >= 75 ? "Tu perfil comparte varios elementos centrales con esta búsqueda." : score >= 50 ? "Hay una base de coincidencia, aunque conviene ajustar el foco antes de postularte." : "La coincidencia es inicial; revisá las brechas antes de enviar tu postulación.";
  return { score, summary, strengths, gaps, missingKeywords, relevantExperience, recommendations, highlight, cvFileName };
}